### PR TITLE
Stylechecker utility output overhaul.

### PR DESCRIPTION
**Pull request by gustavofonseca**
The basic output is now presented as JSON structure. The option
*--assetsdir* lookups, in the given dir, for each asset referenced in
XML. The *--annotated* option now writes the output to a file. The
utility now takes more than one XML a time.

### CODE REVIEW

**Comment by lpanebr** [comment]
"The utility now takes more than one XML a time."

Cool!

Em 16h35 Seg, 02/02/2015, Gustavo Fonseca <notifications@github.com>
escreveu:

**Comment by gustavofonseca** [comment]
;) 

Acabei de disponibilizar essa nova versão. 

pip install packtools —upgrade

ps: se instalar o pygments a saída fica mais legal (pip install pygments)

**Comment by lpanebr** [comment]
Vou testar hj mesmo!

Em 18h34 Seg, 02/02/2015, Gustavo Fonseca <notifications@github.com>
escreveu:

> ;)
>
> Acabei de disponibilizar essa nova versão.
>
> pip install packtools —upgrade
>
> ps: se instalar o pygments a saída fica mais legal (pip install pygments)
>

**Comment by lpanebr** [comment]
Super nice! Good job!!!!
:-D

**Comment by gustavofonseca** [comment]
:+1:

**Pull request merged**
